### ISSUE TITLE
Support o-icons v5

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/o-comments#15]
Currently, o-comments depends on `"o-icons": "^4.0.0"`.

Would it be possible to extend this to `"o-icons": ">=4.0.0 < 6"`?

(For reference, o-buttons [supports both v4 and v5](https://github.com/Financial-Times/o-buttons/blob/master/bower.json).)

**Comment by onishiweb** [comment]
It would need work as `o-buttons` supports the new iconset and currently o-comments-ui does not.

**Comment by JakeChampion** [comment]
#18
