### ISSUE TITLE
Should throw exception if invalid constructor options provided

### ISSUE THREAD

**Issue by aendrew** [Financial-Times/o-comments#27]
Bug

## What
`o-comments` requires an object with attributes `articleId`, `url` and `title`. Leaving one out causes oComments to silently fail.

## Details
I seriously lost about 2 hours this afternoon trying to trace why comments weren't appearing through a React app, then a component library, then finally `o-comments`. If `o-comments` isn't going to initialise due to incomplete constructor arguments, it should throw some kind of exception that indicates a value is missing from the constructor.

If o-comments already does this, it could be because in my case an empty string was being passed as title, which, although valid, was causing comments not to appear.

**Comment by JakeChampion** [comment]
The required fields have been documented as mandatory in the readme --> https://github.com/Financial-Times/o-comments/blob/32a61c6fbde2e9c6e7a41452a5582f2bdc33bc5e/README.md#more-about-the-constructor-config-object

We can look into making it throw an error but that would likely be a breaking change as any consumers that were silently failing would then actually fail and the rest of their JavaScript will not execute.

**Comment by aendrew** [comment]
Maybe instead of throwing an exception it should just log a warning that `o-comments` won't be displayed due to lacking a particular field? That would prevent it from being a breaking change while giving developers more insight into why o-comments might not be displaying.

**Comment by JakeChampion** [comment]
@Financial-Times/content-innovation what do you think should be done in this situation? Shall o-comments release a new major version which throws an error if given invalid options?

**Comment by nickcolley** [comment]
We could start with the suggestion to output a `console.error` as @aendrew has suggested, then if people still find it confusing go for a major version that blows up.
