### ISSUE TITLE
Enable comment alerts on next FT

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/o-comments#3]
![image](https://cloud.githubusercontent.com/assets/224547/15863915/c7ae1fac-2ccc-11e6-9556-cf50c6846479.png)

Lisa Pollack uploaded and commented on an image: comment on article alerts.PNG 

> Hello. Query about comment alerts on Next. Is it a known/expected issue that they don't seem to show up on Next? (Screenshot of how they look on ft.com)

**Comment by tgabe** [comment]
AFAIK, we have not implemented this at Next. I don't recall this being in the current must-have list as well. It's best to raise this with BAs/POs to just add it to the backlog.

**Comment by ironsidevsquincy** [comment]
This did actually used to work. I'm guessing we lost it, for some reason, when switching over to lazy-loading comments

**Comment by tgabe** [comment]
Ack! My bad! I've created a Jira ticket: https://jira.ft.com/browse/NFT-483. Triage group will determine if this should be prioritised or not soon.

**Comment by wheresrhys** [comment]
this works now
